name: native_location_bridge
description: A Flutter package for fetching location and real-time location updates using native Android/iOS code without dependencies.
version: 1.0.1
repository: https://github.com/shubhamdevgupta/native_location_bridge
homepage: https://github.com/shubhamdevgupta/native_location_bridge

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_location_bridge
        pluginClass: MainActivity
      ios:
        pluginClass: AppDelegate

dev_dependencies:
  flutter_test:
    sdk: flutter
