name: native_location_bridge
description: A Flutter package for fetching location and real-time location updates using native Android/iOS code without dependencies.
version: 1.0.0
repository: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
homepage: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_location_bridge
        pluginClass: MainActivity
      ios:
        pluginClass: AppDelegate

